### ISSUE TITLE
Error in 

### ISSUE THREAD

**Issue by sohaibjaved44** [steentottrup/AspNet.Identity.MongoDB#3]
Hi Thanks for this solution, I have been trying to get it working but its telling me this, no work around is  found so far. Can you help me figure out the issue? 
![image](https://cloud.githubusercontent.com/assets/8418548/26363763/781a1e8a-3ffb-11e7-9553-ad32e3f0ec3a.png)

**Comment by steentottrup** [comment]
The expected input Id should be a MongoDB ObjectId, not a integer or any other type. I think that is the problem.

**Comment by sohaibjaved44** [comment]
I have just configured the way its mentioned on github. I have not added any entity yet.

**Comment by steentottrup** [comment]
Well, it's somehow attempting to load the user with the ID 1, so maybe a left-over cookie or something?

**Comment by sohaibjaved44** [comment]
Great thanks, I was struggling to find the issue. It was cookie problem. I have switched the browser and now its working fine.
Thanks.
